COPY dict_units FROM 'C:/Users/fguerrero/OneDrive - Linear Chemicals,SLU/Documentos/R/db.samples/exported\dict_units.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
COPY sample_categories FROM 'C:/Users/fguerrero/OneDrive - Linear Chemicals,SLU/Documentos/R/db.samples/exported\sample_categories.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
COPY suppliers FROM 'C:/Users/fguerrero/OneDrive - Linear Chemicals,SLU/Documentos/R/db.samples/exported\suppliers.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
COPY samples FROM 'C:/Users/fguerrero/OneDrive - Linear Chemicals,SLU/Documentos/R/db.samples/exported\samples.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
COPY supplier_references FROM 'C:/Users/fguerrero/OneDrive - Linear Chemicals,SLU/Documentos/R/db.samples/exported\supplier_references.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
COPY supplier_lots FROM 'C:/Users/fguerrero/OneDrive - Linear Chemicals,SLU/Documentos/R/db.samples/exported\supplier_lots.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
COPY sample_mixtures FROM 'C:/Users/fguerrero/OneDrive - Linear Chemicals,SLU/Documentos/R/db.samples/exported\sample_mixtures.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
COPY mixture_components FROM 'C:/Users/fguerrero/OneDrive - Linear Chemicals,SLU/Documentos/R/db.samples/exported\mixture_components.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
COPY sample_others FROM 'C:/Users/fguerrero/OneDrive - Linear Chemicals,SLU/Documentos/R/db.samples/exported\sample_others.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
